version: '3.4'
services:
  php:
    container_name: php_dev
    mem_limit: 1024m
    cpus: 2
    build:
      context: .
      dockerfile: php.docker
    ports:
      - '80:80'
    stdin_open: true
    tty: true
    volumes:
      - './app:/var/www/'
    depends_on:
      - db
  db:
    container_name: db
    mem_limit: 1024m
    cpus: 2
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aplicatieweb
      MYSQL_USER: claudiu
      MYSQL_PASSWORD: claudiu
    volumes:
      - ./dep/install.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - '9906:3306'
